### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by lambalethuong** [michaelprimez/searchablespinner#29]
In my app I used 2 searchable spinners with id currency1 and currency2.
It work well for most case, except when I just hide the app, screen go to sleep for several seconds.
After that, I turn on the screen and restart app, I faced with crash report:
java.lang.RuntimeException: Unable to start activity ComponentInfo{...MainActivity}java.lang.IllegalArgumentException: wrong state class, expecting View State but received class gr.escsoft.michaelprimez.searchablespinner.SearchableSpinner$SavedState instead. This usually happen when two views of different type have the same id in the same hierarchy. This view's id is id/currency1. Make sure other views do not use the same id.
blah blah blah 
Caused by:java.lang.IllegalArgumentException: wrong state class, expecting View State but received class gr.escsoft.michaelprimez.searchablespinner.SearchableSpinner$SavedState instead. This usually happen when two views of different type have the same id in the same hierarchy. This view's id is id/currency1. Make sure other views do not use the same id. 
at android.view.View.onRestoreInstanceState(View.java:13653)
at gr.escsoft.michaelprimez.searchablespinner.SearchableSpinner.onRestoreInstanceState(SearchableSpinner.java:714)
at android.view.View.dispatchRestoreInstanceState(View.java:13629)
blah blah blah 

I checked and found 2 links familiar with this issue:
https://stackoverflow.com/questions/37113031/wrong-state-class-expecting-view-state-but-received-class-android-widget-compou
https://github.com/HomHomLin/Android-PullToRefreshRecyclerView/issues/4

Hope to see your feedback soon.

**Comment by VEZE** [comment]
+

**Comment by VEZE** [comment]
"+"
