### ISSUE TITLE
I am getting error in android 9.0 (AbsListView Error)

### ISSUE THREAD

**Issue by devileya** [michaelprimez/searchablespinner#46]
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
        at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:4194)
        at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:2463)
        at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7705)
        at android.view.View.createAccessibilityNodeInfoInternal(View.java:7666)
        at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:27237)
        at android.view.View.createAccessibilityNodeInfo(View.java:7649)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1147)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
        at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:67)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sidj23** [comment]
I have this same issue, can someone help us out.
